package cacher

import (
	"fmt"
	"strings"
)

// List of cache key used in malscraper.
const (
	keyAnime               = "mal:anime"
	keyAnimeVideo          = "mal:anime-video"
	keyAnimeEpisode        = "mal:anime-episode"
	keyAnimeReview         = "mal:anime-review"
	keyAnimeRecommendation = "mal:anime-recommendation"
	keyAnimeStats          = "mal:anime-stats"
	keyAnimeCharacter      = "mal:anime-character"
	keyAnimeStaff          = "mal:anime-staff"
	keyAnimeNews           = "mal:anime-news"
	keyAnimeArticle        = "mal:anime-article"
	keyAnimeClub           = "mal:anime-club"
	keyAnimePicture        = "mal:anime-picture"
	keyAnimeMoreInfo       = "mal:anime-more-info"
	keyManga               = "mal:manga"
	keyMangaReview         = "mal:manga-review"
	keyMangaRecommendation = "mal:manga-recommendation"
	keyMangaStats          = "mal:manga-stats"
	keyMangaCharacter      = "mal:manga-character"
	keyMangaNews           = "mal:manga-news"
	keyMangaArticle        = "mal:manga-article"
	keyMangaClub           = "mal:manga-club"
	keyMangaPicture        = "mal:manga-picture"
	keyMangaMoreInfo       = "mal:manga-more-info"
	keyCharacter           = "mal:character"
	keyCharacterArticle    = "mal:character-article"
	keyCharacterClub       = "mal:character-club"
	keyCharacterPicture    = "mal:character-picture"
	keyCharacterOgraphy    = "mal:character-ography"
	keyPeople              = "mal:people"
	keyPeopleNews          = "mal:people-news"
	keyPeopleArticle       = "mal:people-article"
	keyPeoplePicture       = "mal:people-picture"
	keyPeopleChar          = "mal:people-character"
	keyPeopleStaff         = "mal:people-staff"
	keyPeopleManga         = "mal:people-manga"
	keyProducers           = "mal:producers"
	keyProducer            = "mal:producer"
	keyMagazines           = "mal:magazines"
	keyMagazine            = "mal:magazine"
	keyGenres              = "mal:genres"
	keyAnimeWithGenre      = "mal:anime-with-genre"
	keyMangaWithGenre      = "mal:manga-with-genre"
	keyReviews             = "mal:reviews"
	keyReview              = "mal:review"
	keyRecommendations     = "mal:recommendations"
	keyRecommendation      = "mal:recommendation"
	keyUser                = "mal:user"
	keyUserStats           = "mal:user-stats"
	keyUserFavorite        = "mal:user-favorite"
	keyUserFriend          = "mal:user-friend"
	keyUserHistory         = "mal:user-history"
	keyUserReview          = "mal:user-review"
	keyUserRecommendation  = "mal:user-recommendation"
	keyUserClub            = "mal:user-club"
	keyUserAnime           = "mal:user-anime"
	keyUserManga           = "mal:user-manga"
	keySearchCharacter     = "mal:search-character"
	keySearchPeople        = "mal:search-people"
	keySearchUser          = "mal:search-user"
	keySearchClub          = "mal:search-club"
	keySeason              = "mal:season"
	keyTopAnime            = "mal:top-anime"
	keyTopManga            = "mal:top-manga"
	keyTopCharacter        = "mal:top-character"
	keyTopPeople           = "mal:top-people"
	keyNewsList            = "mal:news-list"
	keyNews                = "mal:news"
	keyNewsTag             = "mal:news-tag"
	keyArticle             = "mal:article"
	keyArticleTag          = "mal:article-tag"
	keyArticleList         = "mal:article-list"
	keyClubs               = "mal:clubs"
	keyClub                = "mal:club"
	keyClubMember          = "mal:club-member"
	keyClubPicture         = "mal:club-picture"
	keyClubRelated         = "mal:club-related"
)

func getKey(key string, params ...interface{}) string {
	strParams := []string{key}
	for _, p := range params {
		strParams = append(strParams, fmt.Sprintf("%v", p))
	}
	return strings.Join(strParams, ":")
}
