name: test

on :
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run test
      run: go test -failfast -parallel 1 -cover -mod vendor -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
    - name: Create tag
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}