name: test

on :
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run test
      run: go test -v -cover -mod vendor ./...